### ISSUE TITLE
specify a wait timeout?

### ISSUE THREAD

**Issue by oconnor663** [oconnor663/duct.rs#25]

**Comment by oconnor663** [comment]
We're not doing this, because Unix doesn't really support it. The Python implements this, for example, is to loop with exponentially increasing sleeps, checking the child every so often. I don't like that behavior, because it causes problems in certain edge cases. For example, say I have a child process that takes an hour to run, but I need to be notified as soon as its done (because "done" might mean we killed it from another thread or something). It might not be acceptable to return minutes after the child actually exited. If the answer is "well then don't set an hour-long timeout", that's not great.

**Comment by gibfahn** [comment]
For anyone else finding this issue, if you do want to do timeouts (having considered the above caveats), seems like wait_timeout is the crate to use.

https://docs.rs/wait-timeout/latest/wait_timeout/index.html
https://github.com/alexcrichton/wait-timeout/tree/master

(also refs https://github.com/oconnor663/duct.rs/issues/29)
