### ISSUE TITLE
Change user for subprocess

### ISSUE THREAD

**Issue by TethysSvensson** [oconnor663/duct.rs#55]
Would it be possible to add the ability to change uid/gid before spawning a command?

Specifically I was thinking of adding a function with a similar semantics to `unchecked`, i.e. it will change the entire sub-expression to run as the specified user, so you can both do it easily for the entire expression and for specific parts.

I am not sure whether it would be possible to support windows, but for our use-case it would be fine if this was implemented as `duct::unix::ExpressionExt`.

If you are interested in the feature, I could try creating a PR.

**Comment by oconnor663** [comment]
That could be possible, especially since it looks like `std::process::Command` supports it. That said, I'd only expect it to work as root, right? Would it be just as easy to put `sudo` or `su` in the affected commands, rather than relying on the library to do this?

I'm a little bit inclined to keep `duct` simple, since I want it to work consistently across different platforms and different languages. But let me know what you think, since I don't really know the use cases for setuid/setgid.

**Comment by Idolf** [comment]
My primary use-case is running inside a docker container, where my main entry-point requires root privileges, but runs commands as a lower-privileged user.

Most of them are debian based, which have su installed by default. However `su` only takes a single argument, which introduces the issues of shell escaping. I would prefer to avoid that. If I had to go this route, I would probably install `sudo` or possibly create a fork if I got annoyed enough.

Assuming I install `sudo`, then the remaining annoyance is that the APIs becomes much more clunky. For instance, if you wanted to write this function:

```rust
fn wrap(args1: &[&str], args2: &[&str], use_sudo: bool) -> duct::Expression {
    let mut val = duct::cmd("prg1", args1).pipe(duct::cmd("prg2", args2));
    if use_sudo {
        val.uid(1000).gid(1000)
    } else {
        val
    }
}
```

I would have to write this instead:

```rust
fn wrap(args1: &[&str], args2: &[&str], use_sudo: bool) -> duct::Expression {
    if use_sudo {
        duct::cmd("sudo", ["-u1000", "-g1000", "prg1"].iter().chain(args1)).pipe(duct::cmd(
            "sudo",
            ["-u1000", "-g1000", "prg2"].iter().chain(args2),
        ))
    } else {
        duct::cmd("prg1", args1).then(duct::cmd("prg2", args2))
    }
}
```

That being said, I am not actually sure I would every have to run this complicated an example, so in practice I am not sure it will be **this** bad.

**Comment by oconnor663** [comment]
I think the [`before_spawn`](https://docs.rs/duct/0.12.0/duct/struct.Expression.html#method.before_spawn) method solves this use case now.
