### ISSUE TITLE
The `cmd!` macro does not support trailing commas.

### ISSUE THREAD

**Issue by olson-sean-k** [oconnor663/duct.rs#72]
Using trailing commas with the `cmd!` macro results in errors. Now that `?` has landed, it should be possible to support trailing commas without the need to create additional macro patterns.

For example, this does not build:

```rust
#[rustfmt::skip]
let output = cmd!(
    "ffmpeg",
    "-r", "30",
    "-start_number", "0",
    ...
    "-pix_fmt", "yuv420p",
    "-c:v", "libx264",
    "-y", // trailing comma
).read()?;
```

**Comment by oconnor663** [comment]
Ah you know what, support for this is present in master, but unreleased. I'll clean it up and push a release.

**Comment by oconnor663** [comment]
Done!
