### ISSUE TITLE
Support for process creation flags on Windows

### ISSUE THREAD

**Issue by Boscop** [oconnor663/duct.rs#86]
Would it be possible to add support for process creation flags on Windows, like [this](https://doc.rust-lang.org/std/os/windows/process/trait.CommandExt.html#tymethod.creation_flags)?

(In my current use case I'd like to pass the flag `CREATE_NEW_PROCESS_GROUP` so that my child processes don't get killed by Ctrl-C, because I use the `ctrlc` crate to catch the signal and want to do graceful termination, and that requires that the child processes aren't forcefully killed. Which currently happens because by default they are in the same process group as the parent.)

**Comment by oconnor663** [comment]
Could you handle this case with the [`before_spawn`](https://docs.rs/duct/0.13.4/duct/struct.Expression.html#method.before_spawn) method? It's intended as kind of a catch-all for these sorts of low-level operations.

**Comment by Boscop** [comment]
@oconnor663 Works perfectly, thanks :)
