### ISSUE TITLE
Set environment variables before running sh or sh_dangerous command

### ISSUE THREAD

**Issue by wickedchicken** [oconnor663/duct.rs#87]
Hey, thanks for `duct_sh`!

I was wondering if it would be possible to add envars to be set when calling a command through `sh()` or `sh_dangerous()`. My use case is a "local CI" [command runner](https://github.com/wickedchicken/checklist) which runs a provided list of checks whenever invoked. These tests often need envars set, for example to set dummy database locations or to enable debug logging. While it's possible to embed strings into the shell commands themselves to set the environment variables, `duct` has [native envar support](https://docs.rs/duct/0.13.4/duct/struct.Expression.html#method.env) which seems much cleaner.

Thanks!

**Comment by oconnor663** [comment]
`duct_sh` is intended to be used with all the underlying features of `duct`, including env vars. The `sh` and `sh_dangerous` functions return a `duct::Expression`, so everything should Just Work. Could you give it a try and let me know if it works for you?

**Comment by wickedchicken** [comment]
Indeed, it does! Sorry for the noise, and thanks for the library!

**Comment by oconnor663** [comment]
No problem! Always glad to have users :)
